/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6410d485-01fd-4d9b-a761-fde9c2980a78",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LvwUe9I3G",
    "aws_user_pools_web_client_id": "7b6qhea96shqdb855v73vlvsgl",
    "oauth": {}
};


export default awsmobile;
