/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6410d485-01fd-4d9b-a761-fde9c2980a78",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LvwUe9I3G",
    "aws_user_pools_web_client_id": "7b6qhea96shqdb855v73vlvsgl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3ndcbio5rngmvbio44daktedda.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yiwoqf523jbuxipzl3czbanpmm",
    "aws_user_files_s3_bucket": "race-pace-storage134503-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
